name: linten

on:
  pull_request:
  push:

    
jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "hlint setup"
        uses: haskell-actions/hlint-setup@v2
      - name: "hlint run"
        uses: haskell-actions/hlint-run@v2
        with:
          path: .
          fail-on: warning